
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '9A036C28A6D1368BA4F05A7177C8FA28'
    
_lr_action_items = {'DOUBLE_AO':([0,2,3,4,6,7,9,11,13,16,],[7,7,-8,-9,11,7,7,-7,7,-10,]),'AO':([0,2,3,4,5,6,7,8,9,10,11,12,13,15,16,],[2,2,-8,-9,-3,-6,2,13,2,-4,-7,-5,2,-2,-10,]),'RPAREN':([3,4,5,6,8,10,11,12,14,15,16,],[-8,-9,-3,-6,-1,-4,-7,-5,16,-2,-10,]),'NUMBER':([0,2,7,9,13,],[4,4,4,4,4,]),'$end':([1,3,4,5,6,8,10,11,12,15,16,],[0,-8,-9,-3,-6,-1,-4,-7,-5,-2,-10,]),'LPAREN':([0,2,7,9,13,],[9,9,9,9,9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,9,],[1,14,]),'unaryExp':([0,2,7,9,13,],[5,10,12,5,15,]),'unaryExp2':([0,2,7,9,13,],[6,6,6,6,6,]),'factorExp':([0,2,7,9,13,],[3,3,3,3,3,]),'aritExp':([0,9,],[8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> aritExp','expression',1,'p_expression','parser_rules_v2.py',6),
  ('aritExp -> aritExp AO unaryExp','aritExp',3,'p_aritExp','parser_rules_v2.py',11),
  ('aritExp -> unaryExp','aritExp',1,'p_aritExp_unary','parser_rules_v2.py',24),
  ('unaryExp -> AO unaryExp','unaryExp',2,'p_unaryExp','parser_rules_v2.py',28),
  ('unaryExp -> DOUBLE_AO unaryExp','unaryExp',2,'p_unaryExp_double','parser_rules_v2.py',42),
  ('unaryExp -> unaryExp2','unaryExp',1,'p_unaryExp_double_unaryExp2','parser_rules_v2.py',52),
  ('unaryExp2 -> unaryExp2 DOUBLE_AO','unaryExp2',2,'p_unaryExp_double2','parser_rules_v2.py',56),
  ('unaryExp2 -> factorExp','unaryExp2',1,'p_unaryExp2_factor','parser_rules_v2.py',66),
  ('factorExp -> NUMBER','factorExp',1,'p_factorExp','parser_rules_v2.py',70),
  ('factorExp -> LPAREN expression RPAREN','factorExp',3,'p_factorExp_paren','parser_rules_v2.py',74),
]
